### ISSUE TITLE
Virtual reference field not always created

### ISSUE THREAD

**Issue by Erhannis** [collerek/ormar#123]
**Describe the bug**
Sometimes the virtual reference field is not automatically created, on the appropriate class.

**To Reproduce**
Save this code as `main.py`:

```
from fastapi import FastAPI, Body
import databases
import ormar
from ormar import Model
import sqlalchemy
import pydantic
from pydantic.dataclasses import dataclass
from typing import Optional, List, Dict
from uuid import UUID, uuid4
import asyncio
from enum import Enum
from sqlalchemy_utils import database_exists
 
app = FastAPI()
DATABASE_URL = "sqlite:///db.sqlite"
database = databases.Database(DATABASE_URL)
metadata = sqlalchemy.MetaData()
 
class BaseMeta(ormar.ModelMeta):
    metadata = metadata
    database = database
 
 
 
class ChildObject(ormar.Model):
    class Meta(BaseMeta):
        tablename = "child_object"
    id: UUID = ormar.UUID(primary_key=True, default=uuid4)
 
class ParentObject(ormar.Model):
    class Meta(BaseMeta):
        tablename = "parent_object"
    id: UUID = ormar.UUID(primary_key=True, default=uuid4)
    child: ChildObject = ormar.ForeignKey(ChildObject, default=ChildObject())
 
 
app = FastAPI()
app.state.database = database
 
engine = sqlalchemy.create_engine(DATABASE_URL)
# just to be sure we clear the db before
metadata.drop_all(engine)
metadata.create_all(engine)
 
 
# co = ChildObject()
# await co.save()
```

Now open ipython, as follows: 
 
``` 
C:\Users\USER\FOLDER>ipython
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.
 
In [1]: from main import *
 
In [2]: co = ChildObject()
 
In [3]: await co.save()
Out[3]: ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()
 
c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\IPython\lib\pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395
    396             return _default_pprint(obj, self, cycle)
 
c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\IPython\lib\pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():
 
c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\ormar\models\model.py in __repr__(self)
     34
     35     def __repr__(self) -> str:  # pragma nocover
---> 36         _repr = {k: getattr(self, k) for k, v in self.Meta.model_fields.items()}
     37         return f"{self.__class__.__name__}({str(_repr)})"
     38
 
c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\ormar\models\model.py in <dictcomp>(.0)
     34
     35     def __repr__(self) -> str:  # pragma nocover
---> 36         _repr = {k: getattr(self, k) for k, v in self.Meta.model_fields.items()}
     37         return f"{self.__class__.__name__}({str(_repr)})"
     38
 
c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\ormar\models\newbasemodel.py in __getattribute__(self, item)
    275             value = object.__getattribute__(self, "_convert_json")(item, value, "loads")
    276             return value
--> 277         return object.__getattribute__(self, item)  # pragma: no cover
    278
    279     def _verify_model_can_be_initialized(self) -> None:
 
AttributeError: 'ChildObject' object has no attribute 'parentobjects'
 
In [4]:
```

Note - I suspect it may be related to `default=ChildObject()`.  When I remove the default, things succeed.  (However, I believe there was another, seemingly unrelated, condition under which it succeeded - but I haven't been able to replicate it.)  In testing, btw, it's a little odd that, despite that `childObject` is not `Optional`, a value of `None` still works.  Is that intended?

**Expected behavior**
I would expect `await co.save()` to succeed.  OR, I'd expect a warning or error prior to the one received, informing me that the models could not be correctly configured.

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Versions (please complete the following information):**
 - Database backend used: sqlite
 - Python version: 3.8.0
 - `ormar` version: 0.9.5
 - `pydantic` version: 1.7.3
~~ - if applicable `fastapi` version~~

**Additional context**
~~Add any other context about the problem here.~~

**Comment by collerek** [comment]
The relation fields do not support `default` as of now. 

That's because that even you provide the model as a default, it would not be saved to database on model initialization (you would have to await `__init__()` which is not possible). You would have to provide async helper function and I would have to hijack it and run it synchronously in the background. 

But I don't like the idea of "hidden" database interaction on initialization as it's ugly and might produce unexpected and hard to debug errors when something fails along the way, that would also break whole point of asynchronous orm if some calls are secretly run synchronously.

Even if it would be possible, in your case that's because you call to default (`ChildObject()`) is evaluated during class creation and that's probably not what you would like to do anyway, as this would create only **one** object set by default on all `ParentsObjects`.

It's the same as setting a mutable default value for parameter i.e.:
```python
class A:
    # here one list will be created and shared between all instances
    def __init__(self, param=[]):
        self.param = param


a = A()
a.param.append('test')

# new instance
b = A()
print(b.param)
# prints ['test'] - Ops!
```

Moreover you are calling ChildObject before ParentObject class is constructed, so it basically translates to something like:

```python
class ChildObject(ormar.Model):
    class Meta(BaseMeta):
        tablename = "child_object"

    id: UUID = ormar.UUID(primary_key=True, default=uuid4)

# here relations are not set yet
shared_object = ChildObject()

class ParentObject(ormar.Model):
    class Meta(BaseMeta):
        tablename = "parent_object"

    id: UUID = ormar.UUID(primary_key=True, default=uuid4)
    # you basically pass the same object as default which was created before parent definition
    child: ChildObject = ormar.ForeignKey(ChildObject, default=shared_object)
```

You would have to do something like this
**NOT THIS IS NOT GONNA WORK - default is not supported**
```python
class ChildObject(ormar.Model):
    class Meta(BaseMeta):
        tablename = "child_object"

    id: UUID = ormar.UUID(primary_key=True, default=uuid4)


class ParentObject(ormar.Model):
    class Meta(BaseMeta):
        tablename = "parent_object"

    id: UUID = ormar.UUID(primary_key=True, default=uuid4)
    # do not call it - pass the class as class is callable
    # this will call ChildObject() - so new object, for you on each parent initialization
    child: ChildObject = ormar.ForeignKey(ChildObject, default=ChildObject)
```

But the problem would be that child object produced in this way is not saved in the database, so when you would call:
```python
pa = ParentObject()
await pa.save() #<= here you would get integrity error as default created child primary_key is not stored in a database
```
So you would have to manually call `await pa.child.save()` before calling `await pa.save()` and that's basically the same as creating new instance manually anyway.

As for None by default all relation fields are `nullable`, so if you want to make it required you need to set `nullable=False` on `ForeignKey`. Type hints you provide are used only for linting, since it's more complicated than that (and type hints are optional anyway in `ormar`) `ormar` constructs `pydantic` fields and provide proper types even if you do not. That's why all settings are set in the fields params.

**Comment by Erhannis** [comment]
Ok, seems reasonable.  Perhaps there should be a warning or error, then, if `default` is used in a `ForeignKey` etc. constructor?
