### ISSUE TITLE
some question about ormar

### ISSUE THREAD

**Issue by hidaris** [collerek/ormar#20]
Hello,  I'm looking for an asynchronous orm that supports sqlite on edge devices, is ormar available in production service yet?
Also, one question about api, does the sqlalchemy meta information have to be passed manually, as it seems redundant to pass it on for each model.
```python
class Item(ormar.Model):
    class Meta:
        tablename = "items"

    id: ormar.Integer(primary_key=True)
    name: ormar.String(max_length=100)
    category: ormar.ForeignKey(Category, nullable=True)
```
Probably more friendly.

**Comment by collerek** [comment]
Hi,

I would say it is still in development phase - but I do not expect the api to change drastically along the way (and even if that happens you can always pin a specific version, which you should do as of now).

As for production ready I would say the same. Until I'm quite certain everything works I intend to mark it as a pre-release.
But saying that, right now we have 74 tests with 100% coverage, although for sure not all corner cases are covered (yet), and everything seems to work just fine :). All tests are run against all backends on each push as a part of CI/CD pipeline. 

I also intend to use it in production as soon as I have more time to refactor my current solution based on fastapi, as ormar is something I need for my own use. That means that I will try to fix every issues encountered, and of course all PRs are welcomed. The final decision if you wanna try to solve your problems with ormar is up to you ;)

As for the api - it depends. You can use several databases with different metadata and databases instance for different models. Also you need to pass the connection string to the databases itself (and connect/disconnect it with fastapi etc.), and be able to create/update tables with migrations etc. So you can store the databases and metadata in a place convenient for you.

Otherwise I would have to provide some global config - might consider it along the way.

All tests and examples have it explicitly set to show what is expected from users.
But in reality ormar expects as little as an inner class with name `Meta` with 2 class parameters so there is nothing stopping you from doing something like this:

```python
# define a class with needed parameters and subclass this one in models
class LocalMeta:
    metadata = metadata
    database = database

class Item(ormar.Model):
    # subclass it in each model
    class Meta(LocalMeta):
        # note that you don't even have to provide tablename if your desired name is class.__name__.lower()+'s'
        pass

    id: ormar.Integer(primary_key=True)
    name: ormar.String(max_length=100)
    # note that ForeigKey by default is nullable, don't have to be set explicitly
    categories: ormar.ForeignKey(Category)
```

**Comment by hidaris** [comment]
Thanks for your patience with the answers, and the work on this project, I'll start trying to refactor existing projects with it!
