### ISSUE TITLE
Support low level exceptions

### ISSUE THREAD

**Issue by 8area8** [collerek/ormar#574]
Hello,

Already thank you for this really simple and powerful lib to use! :1st_place_medal: 

While testing the lib, I came across an ayncpg error (UniqueViolationError). It would be interesting to get it in the serializer validation, for:
- avoid handling errors from everywhere
- allow a more accurate and coherent error return

The code (using sqlite for the example):
```py
import ormar
import pytest
import databases
import sqlalchemy
from pydantic import ValidationError

database = databases.Database("sqlite:///::memory:")
metadata = sqlalchemy.MetaData()

pytestmark = pytest.mark.anyio


class MainMeta(ormar.ModelMeta):
    metadata = metadata
    database = database


class Tag(ormar.Model):
    """Categorize the articles."""

    class Meta(MainMeta):
        pass

    id = ormar.Integer(primary_key=True)

    name = ormar.String(max_length=255, nullable=False, unique=True)


@pytest.fixture(autouse=True, scope="module")
def create_test_database():
    engine = sqlalchemy.create_engine("sqlite:///::memory:")
    metadata.create_all(engine)
    yield
    metadata.drop_all(engine)


@pytest.mark.parametrize("anyio_backend", ["asyncio"])
async def test_tag_creation():
    """We can create tags.

    1 - we can create tag with a name
    2 - the name must be unique.
    """
    async with database:
        async with database.transaction(force_rollback=True):
            # 1
            tag = await Tag.objects.create(name="tag1")
            assert tag.name == "tag1"

            # 2
            with pytest.raises(
                ValidationError
            ):  # Ideally, should raise the ValidationError (or the asyncORMException ?)
                await Tag.objects.create(name="tag1")
                # out: sqlite3.IntegrityError: UNIQUE constraint failed: tags.name

```

Thanks for reading

**Comment by collerek** [comment]
Thanks for the nice words! :)

The low level errors depend on backend and driver used -> all of the raise different exceptions from their own libraries.
Trying to catch them all would create unnecessary dependencies and would be a mess (handling 5 x backends x no of exceptions), not to mention that some users want to get the raw exceptions.

If you are using fastapi you can register your own error handlers that will return custom messages instead of failing the application.

The other option is to subclass the QuerySet and provide your own wrappings that catch-all exceptions of a given type and convert them to `ValidationError`. Easy substitution of queryset class is now possible in 0.10.25.
