### ISSUE TITLE
Bug in request generated

### ISSUE THREAD

**Issue by schaulet** [collerek/ormar#73]
Hi,
I have a bug with a request generated when trying to fetch data from a many 2 many relation: 
- the request generated reference a user.id field as a primary key, but the primary key in the model is user.registrationnumber
- I also had some errors when using field name containing capitalized letter ou containing '_'
You will find all the details in the sample below.

OS: Centos 7.9 (docker)
python version: 3.8.3
ormar version: 0.7.3
database backend: postgresql

To reproduce the error i made the script below:
```python
import asyncio
import uuid
from datetime import date, datetime
from os import major
from typing import List, Optional, Union

import databases
import ormar
import sqlalchemy
from fastapi.encoders import jsonable_encoder
from sqlalchemy import func, text
import jsonpickle


DATABASE_URL="postgresql://postgres:postgres@db:5432/test"
database = databases.Database(DATABASE_URL)
metadata = sqlalchemy.MetaData()


class MainMeta(ormar.ModelMeta):
    metadata = metadata
    database = database


class Role(ormar.Model):
    class Meta(MainMeta):
        pass
    name                : str = ormar.Text(primary_key=True)
    order               : int = ormar.Integer(default=0)
    description         : str = ormar.Text()


class Company(ormar.Model):
    class Meta(MainMeta):
        pass
    name                : str = ormar.Text(primary_key=True)


class UserRoleCompany(ormar.Model):
    class Meta(MainMeta):
        pass


class User(ormar.Model):
    class Meta(MainMeta):
        pass
    registrationnumber  : str = ormar.Text(primary_key=True)
    company             : Company = ormar.ForeignKey(Company)
    name                : str = ormar.Text()
    role                : Optional[Role] = ormar.ForeignKey(Role)
    roleforcompanies    : Optional[Union[Company, List[Company]]] = ormar.ManyToMany(Company, through=UserRoleCompany)
    lastupdate          : date = ormar.DateTime(server_default=sqlalchemy.func.now())


async def main():
    if not database.is_connected:
        print("connection to db {}.".format(DATABASE_URL))
        await database.connect()
    ##########################################################################################
    try:
        print("adding role")
        role_0 = await Role.objects.create(name="user", order=0, description = "no administration right")
        role_1 = await Role.objects.create(name="admin", order=1, description = "standard administration right")
        role_2 = await Role.objects.create(name="super_admin", order=2, description = "super administration right")
        assert await Role.objects.count() == 3

        print("adding company")
        company_0 = await Company.objects.create(name="Company")
        company_1 = await Company.objects.create(name="Subsidiary Company 1")
        company_2 = await Company.objects.create(name="Subsidiary Company 2")
        company_3 = await Company.objects.create(name="Subsidiary Company 3")
        assert await Company.objects.count() == 4

        print("adding user")
        user = await User.objects.create(registrationnumber="00-00000", company=company_0, name="admin", role=role_1)
        assert await User.objects.count() == 1

        print("removing user")
        await user.delete()
        assert await User.objects.count() == 0

        print("adding user with company-role")
        companies: List[Company] = [company_1, company_2]
        # user = await User.objects.create(registrationnumber="00-00000", company=company_0, name="admin", role=role_1, roleforcompanies=companies)
        user = await User.objects.create(registrationnumber="00-00000", company=company_0, name="admin", role=role_1)
        # print(User.__fields__)
        await user.roleforcompanies.add(company_1)
        await user.roleforcompanies.add(company_2)

        users = await User.objects.select_related("roleforcompanies").all()
        print(jsonpickle.encode(jsonable_encoder(users), unpicklable=False, keys=True ))

    except Exception as error:
        print(error)


    """

    This is the request generated:
    'SELECT
    users.registrationnumber as registrationnumber,
    users.company as company,
    users.name as name, users.role as role,
    users.lastupdate as lastupdate,
    cy24b4_userrolecompanys.id as cy24b4_id,
    cy24b4_userrolecompanys.company as cy24b4_company,
    cy24b4_userrolecompanys.user as cy24b4_user,
    jn50a4_companys.name as jn50a4_name \n
    FROM users
    LEFT OUTER JOIN userrolecompanys cy24b4_userrolecompanys ON cy24b4_userrolecompanys.user=users.id
    LEFT OUTER JOIN companys jn50a4_companys ON jn50a4_companys.name=cy24b4_userrolecompanys.company
    ORDER BY users.registrationnumber, jn50a4_companys.name'

    There is an error in the First LEFT OUTER JOIN generated:
    ... companys.user=users.id
    should be:
   ... companys.user=users.registrationnumber

    There is also a \n in the midle of the string...

    The execution produce the error: column users.id does not exist
    """

    ##########################################################################################
    if database.is_connected:
        await database.disconnect()
        print("db closed.")




if __name__ == '__main__':
    asyncio.run(main())

```

I'm new to python, sqlalchemy, fastapi anr ormar.... maybe i made some mistakes...
Thanks for this great project.

**Comment by soderluk** [comment]
I'm not sure, but might be related.

I've a simple Many2Many relation that now suddenly started to show errors like `Could not locate column in row for column 'cb6c52_id'`. Was already in previous version 0.7.2. I updated to 0.7.3, but same error generated.

**Comment by collerek** [comment]
OK, thanks for catching that up 👍 

@schaulet there **was** a bug bug also a few remarks:
*  Your code is not PEP8 compliant - seems weird for python developers ( I mean spacing arounf field definition :) )
*  You should avoid columns names that are SQL keywords - like `order` in your example -> some backend will complain (like sqlite). You can always keep the name in ormar/pydantic but just change db name by providing a name argument `order: int = ormar.Integer(default=0, name='sort_order')`
*  You should avoid using `Text` fields as primary keys - will fail on some backends (like mysql) and if you do not provide max lenght (in `Text` you cannot) it might affect performance on some backends (index recalculation). Instead use `String` with max_length set to some number that suit your needs.
*  There was really no option to link two times to one related model (like Company) in your example but in version **0.7.4** there is. But if you do it - you need to provide related_name for all but one relation fields. `ormar` insert second side of relation for you and the name of the relation is calculated for you based on model name if related_name is not provided. 
```python
class User(ormar.Model):
    class Meta(MainMeta):
        pass

    registrationnumber: str = ormar.String(primary_key=True, max_length=1000)
    company: Company = ormar.ForeignKey(Company) # here ormar registers field users on Company model
    name: str = ormar.Text()
    role: Optional[Role] = ormar.ForeignKey(Role)
    roleforcompanies: Optional[Union[Company, List[Company]]] = ormar.ManyToMany(
        Company, through=UserRoleCompany, related_name="role_users" # here you were overwriting the field users
    ) # the solution is to provide related_name different than 'users'. Related name has to be unique.
    lastupdate: date = ormar.DateTime(server_default=sqlalchemy.func.now())
```
If you now try to do this an exception will be raised. 
* If you are using `fastapi` you should connect the db in `shutdown` and `startup` events (see ormar docs or fastapi docs). That way you connect once per request.
* If you are using fastapi you do not need to json the result yourself in the endpoint just return list of ormar Models, that way you should probably also be able to skip jsonpickle
* Yes there is a new line character in raw query but it's inserted by `sqlalchemy` not `ormar` and it's fine as the query is processed anyway
* For now there is no way to add additional fields on Through model yet, so in your case you probably should register new model like CompanyRole and link User -> Company Role as many to many and CompanyRole should link both ro Role and to Company. In your setup if you link directly to Company in m2m there is no way to place the role (`UserRoleCompany`) fields will not be exposed even if you add them. This is on the list of to do - will create a issue for this so this will not slip.

After this to long response - the bug is should be fixed in **0.7.4** - please update and try.

**Comment by collerek** [comment]
@soderluk Yes there was a bug, added your test and it's passing.

But note that many_to_many relations are always added as `weakrefs.proxy` so in your scenario your test might pass or fail depending on when the garbage collector will run and reference will become invalid (it's cleaned in ormar when becomes invalid).

If you want to use the parent model in same query and access freshly added related model you should keep the other reference for the child model. i.e.:

```python
users = {}
        for i in range(1, 6):
            user = await User.objects.get(pk=i)
            users[f"user_{i}"] = user # add a reference to object in example in dict so it's not instantly gc and replaced by new one
            if i % 2 == 0:
                await s1.students.add(user)
            else:
                await s2.students.add(user)

        assert len(s1.students) == 2 # that way you are sure the students are here and are valid
        assert len(s2.students) == 3 # otherwise you need to refresh again from db
```

Note: **I am** thinking about changing many2many to concrete references, but that will create circular references. Python CAN handle this scenario and collect circles when they have no outside reference but it can affect performance, so I need to check it before change like this.

The bug with wrong table prefixes should be fixed in **0.7.4** - please update and try.

**Comment by soderluk** [comment]
@collerek Seems like there's still some issues with having multiple relations to the same model.
When the `related_name` is defined for both the relations, and I'm using the `prefetch_related()` function and need to return both relations, I get a `KeyError: '<related_name>'`.

**Comment by collerek** [comment]
@soderluk will check, can you post a sample here so i make sure it's fixed before next release 😉

**Comment by soderluk** [comment]
@collerek: Of course, here you go. A note on the test, I added the `users` dict to the test, but still it fails, at least for me now when I run this:

```python
from typing import List, Optional

import ormar
import pytest

from app.db.database import db, engine, metadata


class User(ormar.Model):
    class Meta:
        metadata = metadata
        database = db
        tablename = "test_users"

    id: int = ormar.Integer(primary_key=True)
    name: str = ormar.String(max_length=50)


class Signup(ormar.Model):
    class Meta:
        metadata = metadata
        database = db
        tablename = "test_signup"

    id: int = ormar.Integer(primary_key=True)


class Session(ormar.Model):
    class Meta:
        metadata = metadata
        database = db
        tablename = "test_sessions"

    id: int = ormar.Integer(primary_key=True)
    name: str = ormar.String(max_length=255, index=True)
    some_text: str = ormar.Text()
    some_other_text: Optional[str] = ormar.Text(nullable=True)
    teacher: Optional[User] = ormar.ForeignKey(
        User, nullable=True, related_name="teaching"
    )
    students: Optional[List[User]] = ormar.ManyToMany(
        User, through=Signup, related_name="attending"
    )


@pytest.mark.asyncio
@pytest.mark.parametrize("user_id", [1, 2, 3, 4, 5])
async def test_create_users(user_id):
    await User.objects.create(name=f"User {user_id}")


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "name, some_text, some_other_text",
    [
        ("Session 1", "Some text 1", "Some other text 1"),
        ("Session 2", "Some text 2", "Some other text 2"),
        ("Session 3", "Some text 3", "Some other text 3"),
        ("Session 4", "Some text 4", "Some other text 4"),
        ("Session 5", "Some text 5", "Some other text 5"),
    ],
)
async def test_create_session_models(name, some_text, some_other_text):
    await Session(
        name=name, some_text=some_text, some_other_text=some_other_text
    ).save()


@pytest.mark.asyncio
async def test_add_students():
    s1 = await Session.objects.get(pk=1)
    s2 = await Session.objects.get(pk=2)

    users = {}
    for i in range(1, 6):
        user = await User.objects.get(pk=i)
        users[f"user_{i}"] = user
        if i % 2 == 0:
            await s1.students.add(user)
        else:
            await s2.students.add(user)

    assert len(s1.students) > 0
    assert len(s2.students) > 0


@pytest.mark.asyncio
async def test_list_sessions_for_user():
    user = await User.objects.select_related("attending").get(pk=1)

    assert user.attending is not None
    assert len(user.attending) > 0


@pytest.mark.asyncio
async def test_list_sessions_with_teachers_and_students():
    query = Session.objects.prefetch_related(
        [
            "students",
            "teacher",
        ]
    )
    sessions = await query.all()
    assert len(sessions) == 5


@pytest.fixture(autouse=True, scope="module")
def create_test_database():
    metadata.create_all(engine)
    yield
    metadata.drop_all(engine)
```

**Comment by collerek** [comment]
As for the test failing I would recommend to create data either in fixtures or create needed data in one/each method. Pytest do not guarantee the ordering of the test, and making them async even more complicate the things.

But putting that aside that way you should have NoMatch exception, you did not provide the one you get so I assume the check for length of the students fail?

**Comment by soderluk** [comment]
@collerek: For me the data is there, and it gets generated. I've checked it, and added a few asserts that the actual model is found and returned. I know, in a real life scenario I'm adding the data in fixtures, but for these tests I don't see the point in that.

Not sure what you mean that where I should put a NoMatch? If there's a NoMatch exception raised, the test will fail, but such an exception is not raised.

The test (test_add_students) just verifies that there are students, any students added to the `session.students` list, but that fails with `AssertionError: assert 0 > 0`

Is there something I'm missing otherwise?

**Comment by collerek** [comment]
No, no, I mean if the data would not be there ormar would throw the NoMatch -> if you do not get it it's there.

Already identified the error -> fixing as of now ;) (It's error with relation_names)

**Comment by collerek** [comment]
@soderluk Should be fixed in 0.7.5 - can you update and confirm before I close this again ;)

**Comment by soderluk** [comment]
@collerek Confirming that now the relations works again :)

Thank you again for your quick and prompt responses and fixes!

**Comment by collerek** [comment]
OK, so closing (for now :D).

Thanks, for catching that up:)

**Comment by schaulet** [comment]
Thanks for you for all, you make a very good job.

**Comment by collerek** [comment]
@schaulet thanks for nice words - if you like it consider starring the repo to help build bigger community, always easier to catch bugs and find contributors. ;)
