### ISSUE TITLE
First impression and improvements-issues on documentation

### ISSUE THREAD

**Issue by athanhat** [collerek/ormar#77]
Hi @collerek, thank you for sharing this effort with the rest of us, I have just started experimenting with `ormar`. I have managed to run your demo with some problems see below, and I have also managed to test it successfully in a couple of alembic migrations . 

* OS: Ubuntu 18.04
* python version: 3.8.6
* ormar version: 0.7.3
* database backend: sqlite and postgresql

### Quick start demo

```python
tracks = await Track.objects.filter(album__name="Fantasies").all()
assert len(tracks) == 2

tracks = await Track.objects.filter(album__name__iexact="fantasies").all()
assert len(tracks) == 2
```
In the documentation, you are missing `await` keywords and the ".all()" at the end. Apart from that I managed to run it without any problem, excluding the `await` peculiarities (read below).

### Problems with await

I am a newcomer in `async/await` use but I noticed that in python 3.8.6, you cannot have `await` outside function. Is that right ? So for this [bulk_create][1] example from the documentation I had to  do

```python
import asyncio

async def main():
    # create multiple instances at once with bulk_create
    await ToDo.objects.bulk_create(
        [
            ToDo(text="Buy the groceries."),
            ToDo(text="Call Mum.", completed=True),
            ToDo(text="Send invoices.", completed=True),
        ]
    )

if __name__ == '__main__':
    asyncio.run(main())
```
In the same example I noticed that you haven't connected to the database and/or you didn't create an engine. 
But It needs
```python
engine = create_engine("sqlite:///db.sqlite")
...

metadata.create_all(engine)
```
otherwise it results in error, unless the database and the tables have been created. Also in SQLite it seems you don't need to connect using e.g. `database.connect()` command but I tried a similar example in postgresql when I created the tables and I had to use `connect()` otherwise you get the following error.
```python
 File "postgres.py", line 148, in acquire
    assert self._database._pool is not None, "DatabaseBackend is not running"
AssertionError: DatabaseBackend is not running

Process finished with exit code 1
```

OK that is all I wanted to report for your interest and the interest of those newcomers like me that are starting using `ormar`. Thank you again for your kindness to share your code with all of us.

I am planning to use `ormar` to build a large scale web app that is based on microservices architecture. I would like to ask you whether you have used it in production for your projects or you know others that have used it successfully ?

[1]: https://collerek.github.io/ormar/queries/#bulk_create

**Comment by collerek** [comment]
@athanhat Thanks for catching that up in the quickstart! :) Already fixed, will publish with next release. 

Yes the examples especially for query calls have only core logic extracted to not clutter the view. If I would construct models in each example, connect to db, create it etc. each example will become much bigger and a lot of repetition would be needed.

### Async
Yes the whole `async/await` ecosystem cannot be used outside of a function in any version of python since it was introduced. The whole `asyncio` module uses an `event loop` to achieve concurrency and you can only schedule a function for an execution. Whole `async/await` is a syntactic sugar around coroutines/futures on which `asyncio` is build. Since Guido was always against introducing new keywords it used to be really ugly. You had to advance it manually with `next()` call, use `yield from` syntax and return values were returned in exceptions etc. Before you had to do it (manage the coroutines) in your own code, later it was all abstracted away (still happens internally in `asyncio`) but this "limitation" remains - python is not concurrent by design and if you want to use concurrent features you need to explicitly use it. You can `await` functions in some python interpreters (like ipython) but under the hood they do exactly what you did -> wrap it up in `asyncio` call to run it synchronously. When you await a function outside of event loop you just receive the future that yet has to be scheduled/executed, not the result of the function call. All this is implied just by use of `await/async` in `ormar`, cause there is no other way. 

You either have to do it yourself, or other libraries like `fastapi` do it for you. In tests you can also use `pytest-asyncio` to mark your functions as `@pytest.mark.asyncio` and pytest will do it for you. 

**If you want more real life examples than in documentation you can see tests folder. Since they actually have to create and connect to database in most of tests, yet remember that those are tests and not all solutions are suitable to be used in real life.**

### Database creation / connection

Yes, if you use it outside of a other framework where you connect your database, you need to do it on your own. There are disclaimers about connecting to db and creation of db but only in the `fastapi` section of the docs, probably should be more specific in other sections. I'm working on dividing/cleanup of the docs as the ormar grew by quite a lot and it's hard to find some information.

If you use `fastapi` or other web framework you should probably connect there -> in middleware or in startup/shutdown events, to connect once per app start or once per request depending on the framework used. For fastapi a sample events are shown in `fastapi` section of the docs.

Probably should also include more fully-contained examples in the docs that can run "as is".

### Production readiness 

Do I think `ormar` is production ready - short answer - not yet. Cause I believe labeling as "production-ready" requires satisfying a certain number of criteria in regard of testing, features, documentation, api stability etc.

#### Features

Do I use it in production - yes, partially. For a long time I couldn't find async orm that would suit my needs so I had to hack around `pydantic` internals and work around `sqlalchemy` core limitations, that become a technical debt in the long run. That led to creation of `ormar` and I do intend to use it in production to completely replace my current solution but for that I need some other features that are not yet present, namely:
* model inheritance (at least mixins and concrete model inheritance - more on this in #67) - in development
* possibility to declare fields on through models in many-to-many relations - to be added
* possibility to process forward references (i.e. to create self-refering models) - to be added.

If the current scope of ormar satisfies your needs it's for you to decide. I am always happy to add new features and/or accept PRs - that's the whole point of open source software :)

#### Api stability

As for the api stability whenever I can I introduce changes in backward compatible changes. Ormar also follows the release numeration that breaking changes bump the major number, other changes and fixes bump minor number. (0.5.2 -> 0.6.0 - breaking, 0.5.2 -> 0.5.3 - non breaking). Saying that the breaking changes **can** happen (and probably will) but will be reflected in change of version. You should pin the version in your project requirements (which is a best practice anyway).

#### Documentation

As you already discovered the docs also need refinement, clarification and some additions. Moreover since api is still changing there are no docstrings filled and api documentation is not published - which makes it harder for developers to modify ormar itself. (to be added in #69 ).

#### Tests

Although the project is build from scratch with intention to keep 100% test coverage (right now around 160 test) for sure not all paths are sufficiently tested and I intend to improve it over time. The bigger the community around ormar the easier it will be to catch bugs and find contributors, that's why I always ask people to consider starring the repo and sharing the news around it.

#### Summary

Writing all that I saw a lot of libraries that do not meet those requirements marked as production-ready ;) 
Also I intend to both develop/ maintain this project as I need this for my own, and will use it fully in production as soon as missing features will be ready. 

But if that suits your needs is for you to decide. 

As I said all contributions are welcome :)

**Comment by athanhat** [comment]
Great, many thanks for the extensive reply, I'll try to keep you informed on how I am using ormar and the issues I have...
