### ISSUE TITLE
Use sqlalchemy extensions with ormar

### ISSUE THREAD

**Issue by laith43d** [collerek/ormar#81]
Hello, 

Can I use Sqlalchemy extensions like sqlalchemy-mptt among others with ormar? 

Also, in a different scenario, can I utilize Sqlalchemy mixins?  I have a project with tens of mixins, including fields,  computed properties,  and functions? 

I'm planning to use ormar for the next project as soon as it's production-ready. I like the project. It's one of a kind that can make us satisfied to replace Django as a high-performance alternative when performance is a prerequisite. 

Thanks

**Comment by collerek** [comment]
The short answer is **no, you cannot use `sqlalchemy` extensions and mixins**.

The reason is that most (all?) of them are created for `sqlalchemy.orm`, while `ormar` uses only `core` part of the `sqlalchemy`.

So `ormar` is `sqlalchemy.orm` "equivalent", the `sqlalchemy` part is used only to build `Tables`, `Columns` and construct semi-raw sql queries (so using `Text` clauses, escaping characters etc.). 

The whole `sqlalchemy.orm` part, when you initialize `declarative_base`, declare fields, relations etc. is completely separate from `core` and not used by `ormar`.

All async orms (including i.e. `tortoise`) that are based on the `sqlalchemy`, use only the `core` part as the `orm` part was not supporting `asyncio`. That changed in 1.4. alpha version of the package, so you can always try to use this version of `sqlalchemy` but I guess that also mixins and extensions needs to be modified (I think the notation changed when used with async but you need to dig deeper in the `sqlalchemy` docs to check that). That also means that if you want validation with `fastapi` you need to combine it with `pydantic` models and maintain two sets of models (orm & `pydantic`).
