### ISSUE TITLE
How to use distributed models

### ISSUE THREAD

**Issue by jbertman** [collerek/ormar#84]
Liking Ormar so far - thanks for finally trying to bridge the Pydantic gap!

I had a question about how to get a production-like FastAPI design working with Ormar. If I have a file structure such as the following:
```
.
├── Dockerfile
├── REQUIREMENTS.txt
├── alembic
│   ├── README
│   ├── env.py
│   ├── script.py.mako
│   └── versions
├── alembic.ini
└── app
    ├── api
    │   ├── category.py
    │   ├── health.py
    │   └── item.py
    ├── config.py
    ├── db
    │   └── models
    │       ├── category.py
    │       └── item.py
    └── main.py
```
Where `main.py` looks something like:
```
def get_db_uri(user, passwd, host, port, db):
    return f"postgres://{user}:{passwd}@{host}:{port}/{db}"


app = FastAPI(
    title=settings.APP_NAME,
    version=settings.APP_VERSION,
    description=settings.APP_DESCRIPTION,
)

db_url = get_db_uri(
    user=settings.POSTGRES_USER,
    passwd=settings.POSTGRES_PASSWORD,
    host=settings.POSTGRES_HOST,
    port=settings.POSTGRES_PORT,
    db=settings.POSTGRES_DB
)

metadata = sqlalchemy.MetaData()
database = databases.Database(db_url)
app.state.database = database


@app.on_event("startup")
async def startup() -> None:
    database_ = app.state.database
    if not database_.is_connected:
        await database_.connect()


@app.on_event("shutdown")
async def shutdown() -> None:
    database_ = app.state.database
    if database_.is_connected:
        await database_.disconnect()

<SNIP: See https://fastapi.tiangolo.com/tutorial/bigger-applications/ for an example>
```
In `app/db/models/category.py` I might have:
```
from typing import Optional
from enum import Enum
import ormar

class Category(ormar.Model):
    class Meta:
        tablename = "categories"
        metadata = metadata
        database = database

    id: int = ormar.Integer(primary_key=True)
    name: str = ormar.String(max_length=100)
```
1. How can I get the references to metadata and database? Do I need to init them in every model?
2. Is the database reference how Alembic should be learning about the models? Think I'm a bit confused as to how best to lay out the application state and pass the right objects around.

**Comment by collerek** [comment]
In a case like this you should move database initialization to one of the submodules.
Otherwise you would run into circular imports.

So you project structure should look something like:
```
.
├── Dockerfile
├── REQUIREMENTS.txt
├── alembic
│   ├── README
│   ├── env.py
│   ├── script.py.mako
│   └── versions
├── alembic.ini
└── app
    ├── api
    │   ├── category.py
    │   ├── health.py
    │   └── item.py
    ├── config.py
    ├── **[OPTION1] dependencies.py** <- put here the db and other global dependencies later
    ├── db
    │   ├──**[OPTION2] database.py** <- put here just the db declaration, other dependencies go somewhere else
    │   └── models
    │       ├── category.py
    │       └── item.py
    └── main.py
```

In this newly created file you should have the actual declarations for metadata and database, so this part:

```python
# import settings here
# import ModelMeta (not required but better code completion in IDE and type checking)
from ormar import ModelMeta

def get_db_uri(user, passwd, host, port, db):
    return f"postgres://{user}:{passwd}@{host}:{port}/{db}"


db_url = get_db_uri(
    user=settings.POSTGRES_USER,
    passwd=settings.POSTGRES_PASSWORD,
    host=settings.POSTGRES_HOST,
    port=settings.POSTGRES_PORT,
    db=settings.POSTGRES_DB
)

metadata = sqlalchemy.MetaData()
database = databases.Database(db_url)

# declare a BaseMeta that you can inherit in Models to not repeat the code
class BaseMeta(ModelMeta):
    database = database
    metadata = metadata

```

As of now you need to pass db and metadata to each model as `ormar` can support several databases (so you have some models in one mysql db, other part of the app uses different postgress db etc.). 
But the best practice is to subclass the meta in models to comply with DRY (don't repeat yourself) principle.

That way in your models files you can:
```python
from typing import Optional
from enum import Enum
import ormar
# adjust accordingly to your new db file location, you import the same meta in all model files
from app.db.database import BaseMeta

class Category(ormar.Model):
    class Meta(BaseMeta):
        # now you can skip db and meta as it's inherited
        # if you accept default tablename (which is Model.__name__.lower() + 's') by default
        # you can omit the tablename too and just put pass
        tablename = "categories"

    id: int = ormar.Integer(primary_key=True)
    name: str = ormar.String(max_length=100)
```

**Note that you have to subclass (inherit from) the BaseMeta. You cannot just use it as `ormar` sets a lot of internal variables/data on the Model's Meta class and those would get overwritten by each model.**

Always when you need to use some dependency accross the app do not keep it in the main file as you will run into circural import.
The same (but simplified) approach is in the tutorial i.e. https://fastapi.tiangolo.com/tutorial/sql-databases/ where the db goes into `database.py` file.

```
.
└── sql_app
    ├── __init__.py
    ├── crud.py
    ├── database.py **<= here**
    ├── main.py **<= not here**
    ├── models.py
    └── schemas.py
```

Since this file does not import anything from your app it won't fall into loop when file1 imports from file2 and file2 imports from file1. That way in the `main.py` (or anywhere you need it) you can import the database instance. 

Note that if you save it at `app.state` you can access db from there, or you can access it from any `ormar.Model` like `Model.Meta.database` or `model_instance.Meta.database` -> but you should be forced to do this only if you want to run some manual sql query etc.

```python
# adjust accordingly to your new db file location
from app.db.database import database

# rest is as it was
app.state.database = database


@app.on_event("startup")
async def startup() -> None:
    database_ = app.state.database
    if not database_.is_connected:
        await database_.connect()


@app.on_event("shutdown")
async def shutdown() -> None:
    database_ = app.state.database
    if database_.is_connected:
        await database_.disconnect()

```

In `fastapi` tutorials it's often in the same file as the app itself (i.e. main.py) as those are simple/toy examples and the whole application is this main file alone.

As for the alembic you need to import the same metadata that you use for creating your models.
So in above example it would be:

```python
# adjust accordingly to your new db file location
from app.db.database import metadata
```

If you place you alembic outside your app you might need to adjust your `sys.path` during migration run.
You can find sample env file for alembic in `ormar` docs in https://collerek.github.io/ormar/models/migrations/ 

Let me know if that helps.

P.S. If you like `ormar` consider staring the repo in github and spreading the news about it. The more people we get to use it the sooner we can catch all potential bugs and it will be easier to find contributors.

**Comment by paolodina** [comment]
> The more people we get to use it the sooner we [...cut...]

Also we can potentially get more support from 3rd-party projects. For example [FastAPI Users](https://github.com/frankie567/fastapi-users) supports SQLAlchemy async backend, MongoDB async backend, Tortoise ORM backend but not ormar, etc.

**Comment by jbertman** [comment]
@collerek Perfect. Thank you for the help (and elaborative answer), looking forward to using Ormar more!

**Comment by collerek** [comment]
@paolodina Yeah I have it in my pipeline to look what's going in the FastapiUsers repo and add support for ormar but for now I still concentrate on two issues I need for my own (#74 - done, waiting for release, and #78 - to be done) and some refactoring in documentation to flatten the learning curve and reorganize into sections for easier search/navigation.
